apiVersion: v1
kind: Service
metadata:
  name: inference-worker-b
  namespace: inference-lab
spec:
  type: ClusterIP
  selector:
    app: inference-worker-b
  ports:
    - name: http
      port: 8000
      targetPort: 8000
